### ISSUE TITLE
trace: inconsistency in "span name" concept across vendors

### ISSUE THREAD

**Issue by bgpat** [DataDog/opencensus-go-exporter-datadog#13]
I send trace data to DataDog APM and Stackdriver Trace. The APM need unique top-level span name in the same trace, so set the unique name as the span name and the request URL as `resource.name`. Although, the Stackdriver's UI shows the span name as URI.
![image](https://user-images.githubusercontent.com/6045753/45346747-12105a80-b5e5-11e8-8dbd-1f8b37cc9344.png)

How to change the span name? I would like to view pretty trace in both storage backend.

cf. #11

**Comment by gbbr** [comment]
Unfortunately I'm not sure if we can fix this. The concept of operation name in Datadog is different from other APM systems. In Opentracing, as well as in Stackdriver (it seems), operation name is what Datadog calls "resource name".

As you've correctly pointed out yourself, Datadog requires top-level names to be consistent across traces in order to get accurate statistics and have efficient sampling.

**Comment by bgpat** [comment]
I would like to overwrite [`ddSpan.Name`](https://github.com/DataDog/opencensus-go-exporter-datadog/blob/64bc6e2dd67bac4e9c3c1d10d6709d417ee7001e/msgpack.go#L30) anyway, but there is no way now. What do you think about swapping `ddSpan.Name` by the special attribute as well as [`_sampling_priority_v1`](https://github.com/DataDog/opencensus-go-exporter-datadog/blob/master/span.go#L88)?

**Comment by gbbr** [comment]
> I would like to overwrite ddSpan.Name anyway

What do you mean? You can set any name you like by using the OpenCensus API's [`StartSpan`](https://godoc.org/go.opencensus.io/trace#StartSpan) method.

> What do you think about swapping ddSpan.Name by the special attribute as well as _sampling_priority_v1?

You've lost me here. Sampling priorty can be set using a special tag called `sampling.priority` also available as the constant [`ext.SamplingPriority`](https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/ext/tags.go#L13). I'm not sure what you mean by "swapping"

**Comment by bgpat** [comment]
> You can set any name you like by using the OpenCensus API's `StartSpan` method.

In Stackdriver Trace, the span name means `URI`. I want to set consistent name across traces as span name in DataDog, and request URI as span name in Stackdriver. I think backend specified issue should be resolved in each exporter, and I need the exporter option to change span name .

**Comment by gbbr** [comment]
I guess we could add a special `span.name` tag which would overwrite the `Name` property when exporting. Would you like to submit a PR?

**Comment by bgpat** [comment]
I submitted new PR for this issue. Please review.
