### ISSUE TITLE
NewExporter() exits the program if StatsAddr is invalid

### ISSUE THREAD

**Issue by arguile-** [DataDog/opencensus-go-exporter-datadog#18]
If you initialize the exporter with an invalid dogstatd address it exits the program instead of returning an error.

Eg.
```go
dd := datadog.NewExporter(datadog.Options{
	StatsAddr: "invalid_address",
})
```

Results in a log like the below and a program exit.
```
2018/10/25 15:14:50 address invalid_address: missing port in address
```

This is due to:

```go
func newStatsExporter(o Options) *statsExporter {
	endpoint := o.StatsAddr
	if endpoint == "" {
		endpoint = defaultStatsAddr
	}

	client, err := statsd.New(endpoint)
	if err != nil {
		log.Fatal(err) // <--- this
	}
```

It's poor behaviour to terminate the program within a package. Returning an error would require a signature change though. Another option would be to just call the provided `OnError`.

Thoughts?

**Comment by gbbr** [comment]
I agree that it would be nicer to just return the error. I think it'd be ok to make this change at this point.

**Comment by DazWilkin** [comment]
[Most] Other Exporters (Azure, AWS, Jaeger, Prometheus, Stackdriver) do return `(*Exporter, error)`.

While it would require a signature change for Datadog, it would make the Exporter more consistent.

I filed a FR against OpenCensus to correct their documentation (that assumes the returned error):
https://github.com/census-instrumentation/opencensus-website/pull/520
