### ISSUE TITLE
stats: Why does the exporter always send gauge?

### ISSUE THREAD

**Issue by rumyantseva** [DataDog/opencensus-go-exporter-datadog#23]
I was trying to use OpenCensus metrics with the DataDog Go exporter and noticed that for all kind of OpenCensus Views the exporter always send the gauge metric.

In the [source code](https://github.com/DataDog/opencensus-go-exporter-datadog/blob/2bef335f5ffffcfa296102765c21882a9158e52a/stats.go#L80) there is this switch statement:

```go
case *view.CountData:
	return client.Gauge(metricName, float64(data.Value), opt.tagMetrics(row.Tags, tags), rate)

case *view.SumData:
	return client.Gauge(metricName, float64(data.Value), opt.tagMetrics(row.Tags, tags), rate)

case *view.LastValueData:
	return client.Gauge(metricName, float64(data.Value), opt.tagMetrics(row.Tags, tags), rate)
```

So, for `CountData`, `SumData` and `LastValueDate` absolutely the same gauge is always sent. Why?

Thank you.

**Comment by rumyantseva** [comment]
@gbbr can I expect some help here? Or should I contact the DataDog support instead? I really didn't get if this behaviour if expected or not.

**Comment by gbbr** [comment]
@rumyantseva we did notice the issue but possibly nobody got around to it. I handle the `trace` part of the exporter. Possibly @masci can offer further pointers or ideas.

Are you not getting the desired behavior or is this more like a question? I'm not sure what to make of it.

**Comment by rumyantseva** [comment]
@gbbr thank you! 

Yes, I expected different behaviour. For example, for OpenCensus' `view.CountDate` I expected that to have `Count` (https://github.com/DataDog/datadog-go/blob/master/statsd/statsd.go#L341) but not `Gauge`.

I wonder if it's possible to add more tests and examples to this library, so it'll be easier to understand the "translation" from OpenCensus to DataDog.

**Comment by ChristineTChen** [comment]
Hi, @rumyantseva! Thanks for reaching out with this issue :) 

The metric types are all sent as gauges from the exporter because Opencensus stats aggregates them in the process before exporting, [see here](https://opencensus.io/stats/ ). The statsd aggregates local metrics sent from code directly.

In the case of `view.CountData`, it represents the aggregated data for the Count aggregation. To avoid sending these metrics incorrectly to Datadog, we submit them as gauges.

**Comment by rumyantseva** [comment]
@ChristineTChen thank you very mach! Will try to practicing more then :)

**Comment by shivasuri** [comment]
Hi, just thought I'd resurface this as I am running into a similar issue. I want my datadog graphs to illustrate a count (number of requests in a given time window), and not keep track of the historical number of requests. Is there any way of performing this conversion in-app on the datadog side without modifying the metrics' submission? I manually converted the metrics' summaries from `Gauge` to `Count` but this didn't do the trick.

**Comment by demeero** [comment]
> Hi, just thought I'd resurface this as I am running into a similar issue. I want my datadog graphs to illustrate a count (number of requests in a given time window), and not keep track of the historical number of requests. Is there any way of performing this conversion in-app on the datadog side without modifying the metrics' submission? I manually converted the metrics' summaries from `Gauge` to `Count` but this didn't do the trick.

I used `diff` aggregation function in datadog to reach the behavior of graphics which would be similar to `count` metrics.

```
sum(last_10m):diff(sum:<metric_name>{<tag_name>:<tag_value>}.as_count()) > 20
```
