### ISSUE TITLE
proposal: warn when normalizing metric names

### ISSUE THREAD

**Issue by DazWilkin** [DataDog/opencensus-go-exporter-datadog#24]
I'm testing OpenCensus code that applies a prefix to metric names.

The (OpenCensus) code works-as-expected with Prometheus and Stackdriver (exporters) but Datadog appears to strip numerical prefixes (and underscores) from the metric names.

I did not observe (log) notifications from Datadog when attempting to create these.

The metrics appear created albeit with names stripped of the prefix (under underscore).

In the following, the metric names used by the OpenCensus code are respectively:
- `181227_log_rpc_requests`
- `thur181227_log_rpc_requests`
- `thursday_log_rpc_requests`

And result in:

![image](https://user-images.githubusercontent.com/1022400/50493154-8aeac500-09d0-11e9-8ecf-7ade28650850.png)

Recommend: Warnings if OpenCensus metric names are mapped to different names in order to preserve Datadog metric naming requirements.

**Comment by gbbr** [comment]
I'm not sure if this is easily achievable at this point since the caller of the Datadog API has no awareness of this, but let's keep it here for the metrics team to consider.

**Comment by DazWilkin** [comment]
It should be possible.

The Datadog Exporter is provided with OpenCensus metric names. It can apply a check on the Datadog metric naming [rules](https://docs.datadoghq.com/developers/metrics/#naming-metrics) and, if there's a discrepancy emit a log warning that it's having to apply a mapping.

**Comment by hithwen** [comment]
@DazWilkin this is not possible because the exporter does not handle anything related to metric sanitization, this is done in the backend.
