### ISSUE TITLE
Pass OpenCensus tags as Datadog metadata for spans

### ISSUE THREAD

**Issue by julianvmodesto** [DataDog/opencensus-go-exporter-datadog#25]
Currently, OpenCensus tags are passed as Datadog tags for metrics, but OpenCensus tags are not passed as Datadog metadata for trace spans.

**Comment by gbbr** [comment]
I'm having difficulties understanding the issue, can you please provide an example to make it clearer what the problem is?

**Comment by julianvmodesto** [comment]
Oops, sorry! I got confused here and I actually need to be setting OpenCensus Attributes.
