### ISSUE TITLE
proposal: support annotations

### ISSUE THREAD

**Issue by hannahhoward** [DataDog/opencensus-go-exporter-datadog#34]
OpenCensus trace spans support time-based events in the form of [Annotations](https://opencensus.io/tracing/span/time_events/annotation/)  and [MessageEvents](https://opencensus.io/tracing/span/time_events/message_event/).

Currently anything you write to the span with `span.Annotate`, `span.AddMessageSendEvent`, `span.AddMessageReceiveEvent` is ignored by the OpenCensus DataDog exporter.

It would be nice to write these to logs that get tagged with the TraceID & SpanID, so that you can view them when viewing APM data in the DataDog console:
https://docs.datadoghq.com/tracing/advanced_usage/?tab=go#logging

**Comment by gbbr** [comment]
@hannahhoward thanks for bringing this proposal up. We currently do not support this functionality in APM. Logs is a different product, and even though we recently added support for linking log entries to spans, I'm afraid it's currently not possible to do it the other way around. Nevertheless, this is a great idea and I will bring it up with the team. Let's leave this issue open to track the progress.

For reference, we have a similar proposal on the Go tracer for Opentracing: https://github.com/DataDog/dd-trace-go/issues/205

**Comment by hannahhoward** [comment]
Thanks for the response. I get that they're two different products and you'd have to decide as a team if it's the right approach, and if or how it can be done at all.

It would certainly seem at the moment that you'd need a logging agent also running and you'd have to hit that separately to write to the log.

**Comment by luisgonzalex** [comment]
Opencensus and Opentracing have merged to OpenTelemetry. This functionality is now available on OpenTelemetry with Datadog, thus we recommend that users switch to OpenTelemetry if possible. 
 More info: [Connect OpenTelemetry Traces and Logs](https://docs.datadoghq.com/tracing/connect_logs_and_traces/opentelemetry/)
