### ISSUE TITLE
Add support for Float64 Attributes.

### ISSUE THREAD

**Issue by rghetia** [DataDog/opencensus-go-exporter-datadog#37]
opencensus add support for (Float64 Attributes](https://github.com/census-instrumentation/opencensus-go/pull/1033). Add support the same to retrieve Float64 accordingly.

**Comment by gbbr** [comment]
Care to open a PR? All we need is to add the snippet below above [this line](https://github.com/DataDog/opencensus-go-exporter-datadog/blob/master/span.go#L109):
```go
    case float64:
        fallthrough
```
Or similar...

**Comment by rghetia** [comment]
sure
