### ISSUE TITLE
request: add support for B3 and Trace Analytics

### ISSUE THREAD

**Issue by lwc** [DataDog/opencensus-go-exporter-datadog#39]
Looks like there's a bunch of cool new stuff in https://github.com/DataDog/dd-trace-go, but this package doesn't get to benefit from it as it's got a hand-rolled tracer.

Seems like it should be using the main client?

**Comment by gbbr** [comment]
You're right, that would be nicer indeed. But I'm not sure if it's that easy. In the meantime, are there any specific features you're looking for? It would be easier to add those than to do what you're suggesting.

**Comment by lwc** [comment]
Sorry, this was a bit of a late in the day drive by thought from me, but looking at recent commit history in `dd-trace-go` there's a couple of things that stand out:

- B3 propagation: we use B3 for opencensus, if DD now supports it too this opens the door to mid trace wire compatibility betweeen OC and DD - this could be huge for us.
- The recent trace analytics stuff: we're super keen to trial Trace Analytics in DD, but most of our services talk to DD via this package, it's not clear how we'd turn it on.

**Comment by gbbr** [comment]
Thanks for clarifying. Indeed those would be nice to have here as well. We should be adding them soon.

**Comment by gbbr** [comment]
I've created a PR. Note that you should already be able to use Trace Analytics anyway by marking spans of interest with the `ext.EventSampleRate` tag. The value is a float64 between `0` and `1` where `1` means sample 100% of these events and `0.5` would mean sample only 50%.

**Comment by luisgonzalex** [comment]
Due to the merge of OpenCensus and OpenTracing into OpenTelemetry, Datadog has moved focus to [Datadog OpenTelemetry Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/datadogexporter). The APM team has no plans to add support for B3 propagation to this exporter.
