### ISSUE TITLE
stats: support buffered writes to Datadog Statsd

### ISSUE THREAD

**Issue by sargun** [DataDog/opencensus-go-exporter-datadog#50]
Problem:

Datadog statsd does not expose the ability to configure the metrics / statsd client with buffered writes. This means that every write turns into a fairly expensive .operation.

Solution:

Expose configuration of buffered client behaviour to the exporter. See: https://github.com/DataDog/opencensus-go-exporter-datadog/pull/48

**Comment by gbbr** [comment]
Thanks for opening the issue. This seems like a good idea to me.
