### ISSUE TITLE
stats: Flushing stats on close

### ISSUE THREAD

**Issue by asad-awadia** [DataDog/opencensus-go-exporter-datadog#53]
**Trying to do**:  Trying to get stats from a cron job that is running Kubernetes.

**Issue**: The pod is terminated as soon as the cron job is done which doesn't give enough time for statsd to flush the stat. 

**Unknown**: The flush time is set to `client.flushTime = time.Millisecond * 100` but not sure if/why that is/is not enough

**Hacky solution**: Adding a `time.sleep` at the end of the job allows the stat to get exported but obviously don't want to go this route

**Proposing**: When `(e *Exporter) Stop()` [ [link-to-code](https://github.com/DataDog/opencensus-go-exporter-datadog/blob/master/datadog.go#L46) ] is called only the trace exporter is stopped, which allows the spans to be flushed but the stats exporter is not. 

1) Should there be a `e.statsExporter.client.Close()` in that function as well which will force flush the stats?

2) What should be done from the returning error `err := e.statsExporter.client.Close()`?

**Comment by gbbr** [comment]
Good point. I think we should also have an `e.statsExporter.stop`, just like we do for traces. About an error, I'm not sure if there is anything we can do about it, other than let the user know 🤔

**Comment by asad-awadia** [comment]
What do you think about having a stop function for statsExporter that is a wrapper on the client.close i.e.

```
func (s *statsExporter) stop() {
    err := s.client.Close()
    if err != nil { fmt.Println("error occurred when trying to close stats exporter", err)}
}
```

 and then add this [statsExporter#stop] function in the exporter's Stop function

**Comment by gbbr** [comment]
We should likely use `s.opts.onError`. I think it qualifies here too. Would that work?

**Comment by asad-awadia** [comment]
Oh nice, that looks even cleaner - yeah can do that too

Let me put up a PR in a bit

**Comment by asad-awadia** [comment]
hmm, thinking about what test to add 🤔 any thoughts?

**Comment by asad-awadia** [comment]
https://github.com/DataDog/opencensus-go-exporter-datadog/pull/54
