### ISSUE TITLE
proposal: pin dependency versions

### ISSUE THREAD

**Issue by AlexandreYang** [DataDog/opencensus-go-exporter-datadog#56]
Dependencies are not currently pinned, changes in libraries on which this repository depend on may break things.

Example of tests failures due to changes in https://github.com/DataDog/datadog-go: https://circleci.com/gh/DataDog/opencensus-go-exporter-datadog/115?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by gbbr** [comment]
I'm not entirely sure this is a good idea. We want the package to use whatever the user is using in his own `$GOPATH`. Any specific packages you are thinking of? Running `go list -f '{{ join .Deps "\n" }}'` reveals these imports (excluding standard library and `golang.org/x/*`): 

```
github.com/tinylib/msgp/msgp
go.opencensus.io
go.opencensus.io/internal
go.opencensus.io/internal/tagencoding
go.opencensus.io/metric/metricdata
go.opencensus.io/metric/metricproducer
go.opencensus.io/resource
go.opencensus.io/stats
go.opencensus.io/stats/internal
go.opencensus.io/stats/view
go.opencensus.io/tag
go.opencensus.io/trace
go.opencensus.io/trace/internal
go.opencensus.io/trace/tracestate
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/ext
github.com/DataDog/datadog-go/statsd
github.com/hashicorp/golang-lru/simplelru
github.com/philhofer/fwd
github.com/tinylib/msgp/msgp
```

**Comment by AlexandreYang** [comment]
> We want the package to use whatever the user is using in his own $GOPATH.

Yes, I see your point.

If that's the intent, maybe we want to set a cron nightly build on Travis to catch compatibility issues    as early as possible.

**Comment by gbbr** [comment]
Sure. A nightly workflow on CircleCI can't hurt: https://circleci.com/docs/2.0/workflows/#nightly-example

**Comment by alyosha** [comment]
@gbbr I also think this library should manage dependencies internally. I am trying to import it in a project I am working on, but dep keeps resolving the `gopkg.in/DataDog/dd-trace-go.v1` dependency to a version that is incompatible with the latest commit for this library. The only way for downstream dep users to resolve this issue and use the library is to specify an `override` constraint on the transitive `gopkg.in/DataDog/dd-trace-go.v1` dependency. 

According to the official [dep documentation](https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md): 

`Overrides should be used cautiously and temporarily, when possible.`

But that is the only option I have at the moment other than biting the bullet and transitioning completely to modules

**Comment by gbbr** [comment]
@alyosha that is indeed a problem we should address ASAP. Before concluding that this is a sign that this library should manage its dependencies, can you please provide more detail about the problem? Which version of `gopkg.in/DataDog/dd-trace-go.v1` is incompatible with this package? If so, that is a big mistake on our behalf because there should be no breaking changes in dd-trace-go v1.x

**Comment by AlexandreYang** [comment]
> Sure. A nightly workflow on CircleCI can't hurt: https://circleci.com/docs/2.0/workflows/#nightly-example

@gbbr Here is the PR for adding nightly builds to this repo: https://github.com/DataDog/opencensus-go-exporter-datadog/pull/59
