### ISSUE TITLE
Appending tags to metric names?

### ISSUE THREAD

**Issue by jlordiales** [DataDog/opencensus-go-exporter-datadog#60]
Hi there!
I'm trying to understand why the exporter is appending tags to metric names here: https://github.com/DataDog/opencensus-go-exporter-datadog/blob/master/datadog.go#L128

This effectively means that every time a new tag is added to an existing metric, that metric changes name (breaking existing dashboards for instance and loosing the history from the previous one). 

I can see how this would be a thing using plain `statsd` but given how the exporter is using `DogStatsD` directly (https://github.com/DataDog/opencensus-go-exporter-datadog/blob/master/stats.go#L12) I can't think of a good reason (related to #30). 

Thanks!

**Comment by MichaelMure** [comment]
Just stumbled upon the same thing.  Can't see a good reason either.
