### ISSUE TITLE
span: error tag based on span kind and status code

### ISSUE THREAD

**Issue by OmarElGabry** [DataDog/opencensus-go-exporter-datadog#62]
Hi!
We recently realized that some errors in DD don't get flagged/tagged as "errors". In other words, DD counts them as "status: Ok" even though the span status is not Ok (for example, Unauthenticated, Internal, etc). 

Below, are some examples to reproduce the issue
**[1] GRPC Client -> GRPC Server -> GetUser()**

And inside GetUser():
```
ctx, span := trace.StartSpan(ctx, "GetUser")
defer span.End()

// .. some code
span.SetStatus(trace.Status{Code: int32(codes.Internal), Message: "Internal error"})
return
```
Expected: 
- The Span of "GRPC Client" should be flagged as "error" in DD
- The Span of "GRPC Server" should be flagged as "error" in DD
- The Span of "GetUser" should be flagged as "error" in DD

Actual: 
- **The Span of "GRPC Client" is not flagged as "error" in DD**
- The span of "GRPC Server" is flagged as "error" in DD
- The Span of "GetUser" is flagged as "error" in DD

<img width="799" alt="Screen Shot 2020-03-23 at 9 24 09 PM" src="https://user-images.githubusercontent.com/9262504/77434496-56261300-6db7-11ea-9bb5-f0bf5d29f5d9.png">

**[2] HTTP request -> GetUser()**
And inside GetUser():
```
ctx, span := trace.StartSpan(ctx, "GetUser")
defer span.End()

// .. some code
span.SetStatus(trace.Status{Code: int32(codes.Unauthenticated), Message: "could not validate session"})
return
```
Expected: 
- The span trace of "GetUser" should be flagged as "error" in DD

Actual: 
- **The span trace of "GetUser" is not flagged as "error" in DD**

<img width="825" alt="Screen Shot 2020-03-23 at 9 21 39 PM" src="https://user-images.githubusercontent.com/9262504/77434512-5cb48a80-6db7-11ea-8e87-f7ff923e3dc6.png">

This issue is reproducible regardless of the flow mentioned above as long as one of these following cases are met:
- The `span.Type` is set to `client` and the error is 500x
- The `span.Type` is not set and the error is 400x such as Unauthenticated.

After some digging, I found that you guys changed that behavior relying on the fact that all error codes with 400x are not errors / shouldn't be tagged as errors in this PR (https://github.com/DataDog/opencensus-go-exporter-datadog/pull/45). In addition, for some reason, all GRPC client errors that aren't divisible by 400 won't be tagged in DD (ref: https://github.com/DataDog/opencensus-go-exporter-datadog/blob/master/span.go#L75)

> This causes confusion and makes stats/counters less meaningful.
ref: https://github.com/DataDog/opencensus-go-exporter-datadog/issues/44

I believe we should re-visit this part. What makes sense for some cases doesn't necessarily mean it is a general case. In other words, **Unauthenticated** error _is_ an error, and should be tagged as an error. When we write the code, we explicitly return an error, shouldn't that be reflected on DD or hidden?.

Similarly, **Internal** errors from GRPC clients (`span.Type` is set to `client`) _are_ errors and we must be able to see them tagged as errors in DD otherwise we will be hiding errors that worth looking at. 

Thanks and sorry for the long writing :)

**Comment by OmarElGabry** [comment]
Follow up:

I understand that there some applications where it makes sense to hide some errors for the DD counters to look more green LOL. But that's not always the case and that's not the expected behavior. We can't account for all the different scenarios and expectations. 

So what do we do?. 

There are some facts we need to abide by. The fact that we are going to do die _is a fact_. Whether you want to hear it, whether you want to believe it, whether you want people to talk about it, _it is a fact._

Similarly, Internal and Unauthenticated [errors](https://en.wikipedia.org/wiki/Error) are errors. It is a fact. Whether you decided to log it, tag it, look at it, see it in DD, or whatever it is still an error. We can't ignore it, otherwise, we will be deceiving ourselves.

**Comment by gbbr** [comment]
Thanks for taking the time to provide such a deep insight into the problem. I'm happy to help with finding the best (and correct) experience here. Before jumping to the conclusion that there is a problem here, I'd like to make sure that we have a good understanding of HTTP status codes and where each error's responsibility lies. As per the [definition of HTTP status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) it is mentions:

> 4xx client error – the request contains bad syntax or cannot be fulfilled

This means that the error is on the client side. A server serving a 4xx status code does not represent a server error. The server has completed its operation successfully. It is simply a notification to the client that it has sent a bad request.

> 5xx server error – the server failed to fulfil an apparently valid request

A client receiving a 5xx status code should not report an error. The client has submitted a correct request and was notified that the error happened _on the server side_.

For this reason, 4xx errors apply only to client type spans and 5xx errors apply only to server type spans.

If this is all clear and you are mentioning a different problem, then I might've misread your text. If this _is_ the problem you're mentioning, then maybe you can share what type of information you are after in your account, because I'm pretty sure there is a way to find it.

**Comment by OmarElGabry** [comment]
@gbbr Appreciate your explanation.

You are totally right. I am not concerned about whether 400x is on the client-side or the server-side or who is responsible to report it. I am sorry if my text wasn't clear. What I was saying is that:

If we have an Unauthenticated error (or any 4xx) / Internal error  (or any 5xx) - this is an _error_, do you agree with me on that (well, regardless of this is a server/client side)?.

If yes, 

If so, why DD doesn't flag the _trace_ as "status: Error"?. This is what I am talking about: the green color while in fact, it is red. 

The client made a call to the server, the server had an internal error. And yes, the client has submitted a correct request and the error happened on the server-side but the whole trace doesn't get tagged as an error. The server can't work on its own, there must be a client that sends a request asking for data, and when the server fails (5xx), shouldn't we know about this?. 

<img width="472" alt="Screen Shot 2020-03-23 at 9 21 45 PM" src="https://user-images.githubusercontent.com/9262504/77659730-cf0ba300-6f4e-11ea-9561-46a20053e5da.png">
<img width="400" alt="Screen Shot 2020-03-26 at 10 43 40 AM" src="https://user-images.githubusercontent.com/9262504/77659626-b1d6d480-6f4e-11ea-9abe-94fbc986eeba.png">


Here is a real situation:

We got some customers complaining about not being able to use some features. The DD traces and dashboards looked good and nothing abnormal. Everything looked fine for me. A few weeks later, I am going through the traces to realize that some of the Unauthenticated and Internal errors in traces (see the screenshots I added in my earlier post) don't get tagged as errors. And so, I had no idea about them. Whether it is on the client-side or server-side that doesn't deny the fact that there is an error and DD was hiding it. 

Later, we fixed the issue with the unauthenticated users and the internal errors, both were bugs in the code. Yes, we do have other tools for logging, metrics, etc but we also rely on DD to get an estimate on how the service is performing. 

I am sorry for this long text. I know it is super frustrating to read such a long one but I am keen on discussing this. So, I have a few questions left:

(1) What's the rationale behind if the `span.Type` is not set, it is assumed to be like `server` and so only errors with 5xx are deemed to be errors
ref: https://github.com/DataDog/opencensus-go-exporter-datadog/blob/master/span.go#L82

(2) Going back to whether this error is on the client or the server side. Again, you're totally right, and I agree with that. But sometimes the server _can be also a client_. For example:
1. A client makes a request to the server
2. The server makes an HTTP request to another external server - In this case, the server is acting as a client to that external server.
3. The server got back 4xx error and reported it in DD span. Now, from DD perspective, since this is a server, 4xx doesn't represent a server error. How do we deal with that?. 

I guess we can use `&ochttp.Transport{}`. Though, I would prefer to wrap the HTTP request with `trace.StartSpan(ctx, "HTTP")` and `span.End()`. There is a miss-match between what errors does `ochttp` report and what this lib reports for the client - let's keep this aside for now. 

Do you have any other recommendations? 

(3) Is it obvious for the users of this lib that if they added the following:

```
span.AddAttributes(trace.StringAttribute("error", "SERVER - Unauthenticated"))
span.SetStatus(trace.Status{Code: int32(codes.Unauthenticated), Message: "could not validate session"})
return 
```

This will flag the server span as an error in DD regardless of what you mentioned that a 4xx status code does not represent a server error. That's because the `error` attribute is DD specific constants and will override the default behavior. 
ref: https://github.com/DataDog/opencensus-go-exporter-datadog/blob/master/span.go#L119

**Comment by gbbr** [comment]
I think one idea that you are proposing is to accept both 4xx and 5xx as errors when the span kind is not set? If so, I'd be fine with that. Basically this change:
```diff
diff --git a/span.go b/span.go
index 1cc797d..7fb66d1 100644
--- a/span.go
+++ b/span.go
@@ -77,8 +77,13 @@ func (e *traceExporter) convertSpan(s *trace.SpanData) *ddSpan {
 		}
 	case trace.SpanKindServer:
 		span.Type = "server"
-		fallthrough
+		if code.status/100 == 5 {
+			span.Error = 1
+		}
 	default:
+		if code.status/100 == 4 {
+			span.Error = 1
+		}
 		if code.status/100 == 5 {
 			span.Error = 1
 		}
```
Am I correct? Although personally I think it's a better experience to always set the "kind" to get the best value.

I realise there was a lot more to discuss in your comment, but I may not be the most qualified person to answer because there are many facets to the Datadog platform and it might be the case that there is some feature we both don't know about that could've helped you find the error faster. For this reason, I encourage you to reach out to our support team and tell them the exact scenario you went through: a customer reported a problem, you tried to identify it on the platform, and you couldn't because of the listed reasons. This way we'd make sure that a bigger pool of knowledge is participating in resolving your issue.

**Comment by OmarElGabry** [comment]
@gbbr Okay. I reached out to the support team as you suggested and I am waiting for their reply. I will post here once I get some information. Thanks!

**Comment by luisgonzalex** [comment]
Closing as #69 was merged
