### ISSUE TITLE
trace: add more OpenCensus net/http plugin tags

### ISSUE THREAD

**Issue by julianvmodesto** [DataDog/opencensus-go-exporter-datadog#9]
I'm instrumenting my HTTP server with the OpenCensus net/http plugin. First off, this is fantastic and mostly Just Works!

I have 2 possibly related issues with tags:

1. http.status_code tag is missing

I see that the tags http.method, http.path, and http.user_agent are all passed to Datadog, but I'm not seeing more tags in the Datadog trace such as http.status_code.

From my understanding, the OpenCensus net/http plugin is collecting and tagging the status code to the span, but Datadog isn't exporting the status code.

2. traces aren't classified as web/http traces

From my guess, the Datadog trace type (Web, Database, Cache, or Custom) is inferred from first-party/primary tags, is that right? I see that my traces are classified as Custom traces, instead of Web/HTTP traces. Because of this, I don't see my traces as available in the new Datadog Trace Search & Analytics dashboard.

**Comment by julianvmodesto** [comment]
Looks like for (2), we'd need to set the `type` field to `web`

https://github.com/DataDog/dd-trace-go/blob/HEAD/ddtrace/tracer/span.go#L41
https://docs.datadoghq.com/api/?lang=python#send-traces

**Comment by julianvmodesto** [comment]
Actually for (2), I think the best way to do this would be for users using the ochttp plugin to set `ddtrace.SpanType` (`span.type`) tag to `web` in the ochttp handler. Opened https://github.com/census-instrumentation/opencensus-go/issues/843

**Comment by gbbr** [comment]
@julianvmodesto it seems correct to set the `span.type` tag. That will work. Does this solve your problem? If yes, we should close this issue.

**Comment by julianvmodesto** [comment]
That makes sense! Closing
